remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
markdown: GFM

title: [[<a href="/">Arthur Caumartin</a>]<br>٩(^‿^)۶]

description: [[<a href="/">Quelques projets auquels j'ai participé !</a>]]






