remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
markdown: GFM

title: [
Arthur Caumartin<br>
٩(^‿^)۶
]

description: [
[<a href="/"
>
Ici retrouver les liens vers les differents projets auquels j'ai participé !
</a>]
]






